name: caliday
description: "A new Flutter project."
publish_to: 'none'

version: 1.1.0+2

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.0
  flutter_riverpod: ^2.6.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
  flutter_timezone: ^5.0.0
  go_router: ^14.8.1
  flutter_svg: ^2.0.16

  # Анимации (для v1.1)
  # lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#4DA6FF"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"
  web:
    generate: false

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/goro/